apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: finrobot-secrets
  namespace: llm-apps
spec:
  encryptedData:
    OPENAI_API_KEY: "" # TO BE POPULATED BY USER VIA KUBESEAL
    FINNHUB_API_KEY: ""
    FMP_API_KEY: ""
    SEC_API_KEY: ""
    REDDIT_CLIENT_ID: ""
    REDDIT_CLIENT_SECRET: ""
    TWITTER_BEARER_TOKEN: ""
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    MLFLOW_S3_ENDPOINT_URL: ""
    MLFLOW_S3_IGNORE_TLS: ""
  template:
    metadata:
      name: finrobot-secrets
      namespace: llm-apps
